# Generated by Django 5.2.17 on 2026-09-07 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('kind', models.CharField(choices=[('one_off', 'One-off'), ('recurring', 'Recurring')], max_length=10)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('assignment_mode', models.CharField(choices=[('manual', 'Manual'), ('auto_rotate', 'Auto-rotate')], max_length=15)),
                ('next_due_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField()),
                ('due_date_at_completion', models.DateField()),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_logs', to='chores.chore')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='chores.householdmember')),
            ],
        ),
        migrations.AddField(
            model_name='chore',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_chores', to='chores.householdmember'),
        ),
        migrations.AddField(
            model_name='chore',
            name='rotation_pool',
            field=models.ManyToManyField(blank=True, related_name='rotation_chores', to='chores.householdmember'),
        ),
    ]
